arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/l10n/generated
nullable-getter: false
synthetic-package: false
header-insertion-file: lib/l10n/header.txt
use-deferred-loading: false
preferred-supported-locales: [ en, id ]