name: pos_system
description: "ExVen POS Lite - Flutter POS Client with Clean Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # Core dependencies for Clean Architecture POS system
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.7.1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation and development dependencies
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  # Internationalization support
  generate: true
  
  # Assets configuration
  assets:
    - assets/images/
    - assets/icons/
    - assets/config/
